version: '3'
services:
  app:
    build: .
    command: yarn start
    tty: true
    depends_on:
      - mongodb
    volumes:
      - ./index.js:/app/index.js

  mongodb:
    image: mongo:3.4.0
    ports:
      - 27017:27017
      - 28017:28017
    command: mongod --nojournal --replSet "rs" --smallfiles --oplogSize 128
