version: '3'
services:
  stream:
    build: .
    command: yarn start
    tty: true
    volumes:
      - ./stream/:/app/src

  sample:
    build: .
    command: yarn start
    tty: true
    volumes:
      - ./sample/:/app/src

  consumer:
    build: .
    command: yarn start
    tty: true
    volumes:
      - ./consumer/:/app/src

  mongodb:
    image: mongo:3.4.0
    command: mongod --nojournal --replSet "rs" --smallfiles --oplogSize 128

  dbConfig:
    image: mongo:3.4.0
    volumes:
      - ./scripts/:/scripts
    command: bash -c "sleep 10 && chmod +x /scripts/mongodb_config.sh && ./scripts/mongodb_config.sh"
    depends_on:
      - mongodb

  topic:
    image: ches/kafka
    command: "kafka-topics.sh --create --topic kittens --replication-factor 1 --partitions 1 --zookeeper zookeeper:2181"
    depends_on:
      - zookeeper
      - kafka

  zookeeper:
    image: zookeeper:3.4
    ports:
      - "2181:2181"

  kafka:
    image: ches/kafka
    ports:
      - "9092:9092"
    environment:
      ZOOKEEPER_IP: zookeeper
